on:
  issues:
    types: 
      - labeled

jobs:
  Broadcast:
    if: ${{ github.event.label.name == 'Hiring' }}
    runs-on: ubuntu-latest
    steps:
      - name: Issue Parser
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/Opportunity.yml
      - run: | 
          JSON=`echo '${{ steps.issue-parser.outputs.jsonString }}'`
          echo $JSON
          com=`echo $(jq -r '.company' <<< "$JSON")`
          reg=`echo $(jq -r '.registration' <<< "$JSON")`
          jd=`echo $(jq -r '.jd' <<< "$JSON")`
          echo "<h1> Opprtunity from `echo $com` </h1> <div> <h2>Job Description</h2><div>`echo $jd` </div></div><div>Interested students please apply here: `echo $reg`<div>" > temp.html
              
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{SECRETS.EMAIL}}
          password: ${{SECRETS.PASSWORD}}
          subject: Opportunity for you
          to: github-campus-group@smail.iitm.ac.in
          cc: ce20b112@smail.iitm.ac.in
          from: GitHub Campus Expert
          html_body: file://temp.html
          secure: true
          ignore_cert: true
          convert_markdown: true
          priority: low
          
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Thank you very much for this opportunity.
            We have forwarded it to the students ⭐⭐.
            
